# Generated by Django 5.2.6 on 2025-10-20 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutoring', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Grupal'), ('urgent', 'Urgente'), ('followup', 'Seguimiento')], default='individual', max_length=20)),
                ('reason', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('performance_level', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('regular', 'Regular'), ('low', 'Bajo'), ('critical', 'Crítico')], default='regular', max_length=10)),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='low', max_length=10)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.tuteeprofile')),
            ],
        ),
    ]
