# Generated by Django 5.2.6 on 2025-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologysession',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologysession',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
