# Generated by Django 5.2.6 on 2025-12-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorComplianceReport',
        ),
    ]
