# Generated by Django 5.2.6 on 2025-09-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TUTOR', 'Tutor'), ('TUTEE', 'Tutorado'), ('SUBAC', 'Subdirección Académica'), ('COORDAC', 'Coordinación Académica'), ('COORDINST', 'Coordinación Institucional'), ('JEFEDEPTO', 'Jefe de Departamento Académico'), ('JEFEDEPTODES', 'Jefe de Departamento de Desarrollo')], max_length=50),
        ),
    ]
