# Generated by Django 5.2.6 on 2025-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('TUTOR', 'Tutor'), ('TUTEE', 'Tutorado'), ('SUBAC', 'Subdirección Académica'), ('COORDAC', 'Coordinación Académica'), ('COORDINST', 'Coordinación Institucional'), ('JEFEDEPTO', 'Jefe de Departamento Académico'), ('JEFEDEPTODES', 'Jefe de Departamento de Desarrollo'), ('PSYCHOLOGIST', 'Psicólogo')], max_length=50, null=True),
        ),
    ]
