# Generated by Django 5.2.6 on 2025-09-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ABSENCE', 'Inasistencia Reiterada'), ('LOW_PERFORMANCE', 'Bajo Rendimiento Académico'), ('OTHER', 'Otro Motivo')], max_length=50)),
                ('description', models.TextField(verbose_name='Descripción de la Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='¿Atendida?')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido de la Guía')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Fecha y Hora Programada')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('COMPLETED', 'Realizada'), ('CANCELED', 'Cancelada'), ('NO_SHOW', 'Inasistencia')], default='SCHEDULED', max_length=50)),
                ('session_summary', models.TextField(blank=True, verbose_name='Resumen de la Sesión')),
                ('agreements', models.TextField(blank=True, verbose_name='Acuerdos y Compromisos')),
            ],
        ),
        migrations.CreateModel(
            name='TuteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio General')),
            ],
        ),
    ]
