# Generated by Django 5.2.6 on 2025-09-17 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='tutee',
            field=models.ForeignKey(limit_choices_to={'role': 'TUTEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.period', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='session',
            name='tutee',
            field=models.ForeignKey(limit_choices_to={'role': 'TUTEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutee_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='assigned_tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tutees', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Asignado'),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'TUTEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
