# Generated by Django 5.2.6 on 2025-10-20 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicdepartment_academicperiod_academiccareer_and_more'),
        ('tutoring', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('evaluation_metrics', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En Revisión'), ('approved', 'Aprobado'), ('active', 'Activo'), ('completed', 'Completado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_actionprograms', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicdepartment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicperiod')),
            ],
        ),
    ]
