# Generated by Django 5.2.6 on 2025-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_actionprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='activity_description',
            field=models.TextField(blank=True, verbose_name='Descripción / instrucciones de la actividad'),
        ),
        migrations.AddField(
            model_name='session',
            name='activity_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de actividad (1-12)'),
        ),
        migrations.AddField(
            model_name='session',
            name='activity_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título de la actividad'),
        ),
        migrations.AddField(
            model_name='session',
            name='kind',
            field=models.CharField(choices=[('PLAN', 'Sesión del programa (12 PIT)'), ('EXTRA', 'Sesión extra (solicitada)')], default='PLAN', max_length=10, verbose_name='Tipo de sesión'),
        ),
    ]
