# Generated by Django 5.2.6 on 2025-11-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_session_activity_description_session_activity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='activity_material',
            field=models.FileField(blank=True, null=True, upload_to='tutoring/activities/', verbose_name='Material PDF'),
        ),
    ]
