# Generated by Django 5.2.6 on 2025-11-26 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicdepartment_academicperiod_academiccareer_and_more'),
        ('tutoring', '0005_session_activity_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.career', verbose_name='Carrera')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.period', verbose_name='Período')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
