# Generated by Django 5.2.6 on 2025-11-26 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_tutorgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteeprofile',
            name='assigned_tutor',
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutees', to='tutoring.tutorgroup', verbose_name='Grupo de Tutoría'),
        ),
    ]
