# Generated by Django 5.2.6 on 2025-12-03 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_remove_tuteeprofile_assigned_tutor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tutoring.tutorgroup', verbose_name='Grupo de Tutoría'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TUTEE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutee_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Tutorado (solo si es individual)'),
        ),
    ]
