# Generated by Django 5.2.6 on 2025-12-03 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_session_group_alter_session_tutee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Asistió'), ('ABSENT', 'No asistió'), ('LATE', 'Llegó tarde'), ('JUSTIFIED', 'Falta justificada')], default='PRESENT', max_length=20, verbose_name='Estado de asistencia')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tutoring.session')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tutoring.tuteeprofile')),
            ],
            options={
                'unique_together': {('session', 'tutee')},
            },
        ),
    ]
