# Generated by Django 5.2.6 on 2025-12-03 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_sessionattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCoordinatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_assigned', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación tutor-coordinador',
                'verbose_name_plural': 'Asignaciones tutor-coordinador',
                'unique_together': {('tutor', 'coordinator')},
            },
        ),
    ]
