# Generated by Django 5.2.6 on 2025-12-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_tutorcoordinatorassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, verbose_name='Periodo')),
                ('title', models.CharField(max_length=200, verbose_name='Título del reporte')),
                ('content', models.TextField(verbose_name='Descripción / contenido del reporte')),
                ('status', models.CharField(choices=[('SENT', 'Enviado al coordinador'), ('REVIEWED', 'Revisado'), ('RETURNED', 'Devuelto al tutor')], default='SENT', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tutoring_reports', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de tutoría',
                'verbose_name_plural': 'Reportes de tutoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
