# Generated by Django 5.2.6 on 2025-12-04 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_tutoringreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Fecha y hora de la entrevista')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Tema / motivo de la entrevista')),
                ('summary', models.TextField(blank=True, verbose_name='Informe de la entrevista (lo hablado con el alumno)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('COMPLETED', 'Realizada'), ('CANCELED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutee', models.ForeignKey(limit_choices_to={'role': 'TUTEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_tutee', to=settings.AUTH_USER_MODEL, verbose_name='Tutorado')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevista de tutoría',
                'verbose_name_plural': 'Entrevistas de tutoría',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
