# Generated by Django 5.2.6 on 2025-12-04 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_tutoringinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tutoring/reports/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo adjunto (PDF)'),
        ),
    ]
