# Generated by Django 5.2.6 on 2025-12-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_tutoringreport_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringreport',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Retroalimentación del coordinador'),
        ),
        migrations.AddField(
            model_name='tutoringreport',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retroalimentación'),
        ),
    ]
