# Generated by Django 5.2.6 on 2025-12-04 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_tutoringreport_feedback_tutoringreport_feedback_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringreport',
            name='attachment',
            field=models.FileField(blank=True, help_text='Sube el archivo Excel del reporte (formato .xlsx o .xls).', null=True, upload_to='tutoring/reports_excels/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='Archivo Excel'),
        ),
    ]
