# Generated by Django 5.2.6 on 2025-12-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_alter_tutoringreport_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringreport',
            name='status',
            field=models.CharField(choices=[('SENT', 'Enviado al coordinador'), ('REVIEWED', 'Revisado'), ('RETURNED', 'Devuelto al tutor'), ('SENT_TO_HEAD', 'Enviado al Jefe de Departamento')], default='SENT', max_length=20, verbose_name='Estado'),
        ),
    ]
