# Generated by Django 5.2.6 on 2025-12-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0016_alter_tutoringreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringreport',
            name='sent_to_head_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
