# Generated by Django 5.2.6 on 2025-12-05 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicdepartment_academicperiod_academiccareer_and_more'),
        ('tutoring', '0017_tutoringreport_sent_to_head_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLIED', 'Cumplió con los objetivos'), ('NOT_COMPLIED', 'No cumplió con los objetivos')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_compliances', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_compliances', to='academic.period')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coordinator', 'tutor', 'period')},
            },
        ),
    ]
