# Generated by Django 5.2.6 on 2025-12-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicdepartment_academicperiod_academiccareer_and_more'),
        ('tutoring', '0018_tutorcompliance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='tutor_compliance_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_compliance_reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_compliance_reports', to='academic.period')),
            ],
            options={
                'unique_together': {('coordinator', 'period')},
            },
        ),
    ]
