# Generated by Django 5.2.6 on 2025-12-07 19:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicdepartment_academicperiod_academiccareer_and_more'),
        ('tutoring', '0019_tutorcompliancereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorGroupCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='tutoring/group_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Constancia (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(limit_choices_to={'role': 'COORDINST'}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_group_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador institucional')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tutoring.tutorgroup', verbose_name='Grupo de tutoría')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_certificates', to='academic.period', verbose_name='Período')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Constancia por grupo',
                'verbose_name_plural': 'Constancias por grupo',
                'unique_together': {('tutor', 'group', 'period')},
            },
        ),
    ]
