# Generated by Django 5.2.6 on 2025-12-07 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0020_tutorgroupcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorgroupcertificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente validación SUBAC'), ('APPROVED', 'Validada por SUBAC'), ('REJECTED', 'Rechazada por SUBAC')], default='PENDING', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tutorgroupcertificate',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación'),
        ),
        migrations.AddField(
            model_name='tutorgroupcertificate',
            name='validated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUBAC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_group_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
    ]
